version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mini_project5
    overwrite: true

permissions:
  - object: /home/ec2-user/mini_project5
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

  - object: /home/ec2-user/mini_project5/scripts/deploy.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

  - object: /home/ec2-user/mini_project5/scripts/install_dependencies.sh
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 1800
      runas: ec2-user
